### ISSUE TITLE
Tinkers'Evolution crash bug with RedstoneRepositoryRevolved

### ISSUE THREAD

**Issue by EringMantis831** [phantamanta44/tinkers-evolution#120] opened 2022-02-20 03:56 UTC
Game will crash when installed TConEvo and RedstoneRepositoryRevolved[Latest Version] in a same game.
I think there's a compatible bug in ur mod. The bug made your mode can't compatible RRR-1.12.2-2.0.0[realese]
Fix it, plz

**Comment by phantamanta44** [comment] 2023-10-24 21:16
duplicate of #114

**Closed as completed by phantamanta44** 2023-10-24 21:16 UTC
